### ISSUE TITLE
Access the button not only from the readme

### ISSUE THREAD

**Issue by laughedelic** [willklein/github-markdown-menu#10]
I almost never open Readme in a separate view, normally I just read it from the repo root page. So for me this button would be much more useful if it appeared there. 
Also, as there is a plugin button in the Chrome toolbar, is it possible to access the TOC from there? When I'm in the middle of a big readme, it's not so convenient to croll all the way up to jump to some other section..

**Comment by willklein** [comment]
Hi @laughedelic, thanks so much for the input!

First, you should be seeing the button on the repo root page. Well, the button is missing its icon and it looks like an empty box, but I'm pushing a fix for that today. I usually view READMEs the same way. See #9.

Second, I like your idea to display the ToC from the button in the Chrome Menu. I thought about docking the navigation somehow for when you scroll a large README, but I think your selection is easier to implement. I'll create a new issue for this.

Thanks!

**Comment by laughedelic** [comment]
Great that you like the idea. 
I see the empty square icon if I open a readme file, but I still don't see it on the root page:

<img width="922" alt="screen shot 2016-04-12 at 18 54 04" src="https://cloud.githubusercontent.com/assets/766656/14468495/286aa446-00e0-11e6-8f41-ea94b28898c8.png">

Can it be that it interferes with the refined-github plugin?

**Comment by willklein** [comment]
Yep, that's why! I'll look into making it work with refined-github. I could also port this to refined-github and have it work with everything else they're doing. If you think this should be part of their extension, please comment on sindresorhus/refined-github#151. I'm not sure what's best for the project, and I'm happy to have it either way.
